version: '3.8'

services:
  # 1. DATABASE SERVICE
  db_app2:
    image: mysql:8.0
    container_name: app2_db
    restart: always
    environment:
      MYSQL_DATABASE: db_app2_nama      # Nama DB sesuai target import tadi
      MYSQL_ROOT_PASSWORD: "dbleni123!" # Password root
    volumes:
      - mysql_data_app2:/var/lib/mysql
    networks:
      - app2-network
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306" # Port Host 3307

  # 2. BACKEND SERVICE (Node.js)
  backend_app2:
    build: ./backend
    container_name: app2_api
    restart: always
    ports:
      - "5001:5001" # Port Host 5001 -> Container 5001
    environment:
      # Konfigurasi Server
      - PORT=5001
      - NODE_ENV=production
      
      # Konfigurasi Database
      - DB_HOST=db_app2     # Service Name database
      - DB_USER=root        
      - DB_PASSWORD=dbleni123!
      - DB_NAME=db_app2_nama
      
      # Konfigurasi Keamanan & URL
      - JWT_SECRET=leni12345678
      - FRONTEND_URL=https://pengadilannegerimanokwari.cloud
      - OTP_EXPIRES_MINUTES=10
      
      # Konfigurasi Email (Gmail)
      - EMAIL_USER=leniwariyanti672@gmail.com
      - EMAIL_PASS=vfhf pdbm btkt bouy
    volumes:
      - ./backend_uploads:/app/public
    depends_on:
      - db_app2
    networks:
      - app2-network

  # 3. FRONTEND SERVICE (React)
  frontend_app2:
    build:
      context: ./frontend
      args:
        # KOREKSI: Hapus /v1 agar sesuai dengan server.js
        VITE_API_BASE_URL: "https://pengadilannegerimanokwari.cloud/api"
    container_name: app2_web
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend_app2
    networks:
      - app2-network

networks:
  app2-network:
    driver: bridge

volumes:
  mysql_data_app2: